db-uri = "mysql://authenticator:secret@127.0.0.1:32820/"
db-schemas = "myrest_fixture, myrest_hidden"
db-anon-role = "myrest_anon"
db-aggregates-enabled = true
db-tx-end = "commit-allow-override"
db-max-rows = 1
jwt-secret = "really-long-secret-key-that-is-at-least-32-chars-long"
