db-uri = "mysql://authenticator:secret@127.0.0.1:43306/"
db-schemas = "myrest_fixture"
db-anon-role = "myrest_anon"
db-tx-end = "commit-allow-override"
jwt-secret = "really-long-secret-key-that-is-at-least-32-chars-long"
