package httpapi

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/jonbaldie/myrest/internal/config"
	"github.com/jonbaldie/myrest/internal/schemacache"
)

const openAPIContentType = "application/openapi+json"

// writeRoot answers GET /. It serves the OpenAPI document from the schema
// cache and the privileges of the active database role, unless openapi-mode
// is disabled or db-root-spec replaces the body.
func (s *Service) writeRoot(writer http.ResponseWriter, request *http.Request) {
	if s.settings.OpenAPI.Mode == config.OpenAPIModeDisabled {
		writeNoHandler(writer, request)
		return
	}

	role, ok := s.requestRole(writer, request)
	if !ok {
		return
	}

	if name := strings.TrimSpace(s.settings.DB.RootSpec); name != "" {
		s.writeRootSpec(writer, request, role, name)
		return
	}

	doc := s.openAPIDocument(role)
	writer.Header().Set("Content-Type", openAPIContentType)
	writer.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(writer).Encode(doc)
}

func (s *Service) writeRootSpec(
	writer http.ResponseWriter,
	request *http.Request,
	role schemacache.Role,
	name string,
) {
	if s.caller == nil {
		writeNoHandler(writer, request)
		return
	}
	database, routineName, err := splitRootSpec(name)
	if err != nil {
		writeFailure(writer, http.StatusInternalServerError, codeMySQLDatabaseFailure, err.Error())
		return
	}
	requested := requestedResource{role: role, database: database, name: routineName}
	routine, ok := s.admitRoutineResource(writer, requested)
	if !ok {
		return
	}
	result, err := s.caller.Call(
		request.Context(),
		role,
		routine,
		map[string]any{},
		CallOptions{},
	)
	if err != nil {
		s.log.Printf("db-root-spec %s: %v", name, err)
		writeDatabaseFailure(writer, err)
		return
	}
	writeJSON(writer, http.StatusOK, result)
}

func splitRootSpec(name string) (database, routine string, err error) {
	database, routine, found := strings.Cut(strings.TrimSpace(name), ".")
	if !found || database == "" || routine == "" || strings.Contains(routine, ".") {
		return "", "", fmt.Errorf("db-root-spec %q must be database.routine", name)
	}
	return database, routine, nil
}

func (s *Service) openAPIDocument(role schemacache.Role) map[string]any {
	paths := s.openAPIPaths(role)
	doc := map[string]any{
		"swagger": "2.0",
		"info": map[string]any{
			"title":       "myrest API",
			"description": "This is a dynamic API generated by myrest",
			"version":     "1.0",
		},
		"paths": paths,
	}
	applyOpenAPIBase(doc, reportedBaseURL(s.settings.OpenAPI.ServerProxyURI, s.URL()))
	applyOpenAPISecurity(doc, s.settings.OpenAPI.SecurityActive)
	return doc
}

func (s *Service) openAPIPaths(role schemacache.Role) map[string]any {
	snapshot := schemacache.ReadSnapshot(s.cache)
	followPrivileges := s.settings.OpenAPI.Mode != config.OpenAPIModeIgnorePrivileges
	paths := map[string]any{
		"/": map[string]any{
			"get": map[string]any{
				"tags":      []string{"Introspection"},
				"summary":   "OpenAPI description (this document)",
				"produces":  []string{openAPIContentType, "application/json"},
				"responses": map[string]any{"200": map[string]any{"description": "OK"}},
			},
		},
	}
	s.addOpenAPITables(paths, snapshot, role, followPrivileges)
	s.addOpenAPIRoutines(paths, snapshot, role, followPrivileges)
	return paths
}

func (s *Service) addOpenAPITables(
	paths map[string]any,
	snapshot schemacache.Snapshot,
	role schemacache.Role,
	followPrivileges bool,
) {
	for _, id := range schemacache.TableIDsFrom(snapshot) {
		if !s.settings.HasDatabase(id.Database) {
			continue
		}
		methods := ignorePrivilegeTableMethods(snapshot, id)
		if followPrivileges {
			requested := requestedResource{role: role, database: id.Database, name: id.Name}
			methods = tableAllowMethods(snapshot, requested)
		}
		if len(methods) == 0 {
			continue
		}
		paths["/"+id.Name] = pathItemFromMethods(methods)
	}
}

func (s *Service) addOpenAPIRoutines(
	paths map[string]any,
	snapshot schemacache.Snapshot,
	role schemacache.Role,
	followPrivileges bool,
) {
	for _, routine := range schemacache.RoutinesFrom(snapshot) {
		if !s.settings.HasDatabase(routine.ID.Database) {
			continue
		}
		if followPrivileges {
			requested := requestedResource{role: role, database: routine.ID.Database, name: routine.ID.Name}
			admitted, ok := routineResource(snapshot, requested)
			if !ok {
				continue
			}
			routine = admitted
		}
		paths["/rpc/"+routine.ID.Name] = pathItemFromMethods(routineAllowMethods(routine))
	}
}

func applyOpenAPISecurity(doc map[string]any, active bool) {
	if !active {
		return
	}
	doc["securityDefinitions"] = map[string]any{
		"JWT": map[string]any{
			"type":        "apiKey",
			"name":        "Authorization",
			"in":          "header",
			"description": `Add the token prepending "Bearer " (without quotes) to it`,
		},
	}
	doc["security"] = []map[string]any{{"JWT": []any{}}}
}

func ignorePrivilegeTableMethods(snapshot schemacache.Snapshot, id schemacache.TableID) []string {
	methods := []string{
		http.MethodOptions,
		http.MethodGet,
		http.MethodHead,
	}
	if schemacache.IsWritableIn(snapshot, id) {
		methods = append(methods, http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete)
	}
	return methods
}

func pathItemFromMethods(methods []string) map[string]any {
	item := map[string]any{}
	for _, method := range methods {
		switch method {
		case http.MethodGet:
			item["get"] = openAPIOperation("OK")
		case http.MethodPost, http.MethodPut:
			item[strings.ToLower(method)] = openAPIOperation("Created")
		case http.MethodPatch, http.MethodDelete:
			item[strings.ToLower(method)] = openAPIOperation("No Content")
		}
	}
	return item
}

func openAPIOperation(statusDescription string) map[string]any {
	status := "200"
	switch statusDescription {
	case "Created":
		status = "201"
	case "No Content":
		status = "204"
	}
	return map[string]any{
		"responses": map[string]any{
			status: map[string]any{"description": statusDescription},
		},
	}
}

func applyOpenAPIBase(doc map[string]any, base string) {
	parsed, err := url.Parse(base)
	if err != nil || parsed.Host == "" {
		return
	}
	host := parsed.Hostname()
	if port := parsed.Port(); port != "" {
		host = host + ":" + port
	}
	doc["host"] = host
	if parsed.Scheme != "" {
		doc["schemes"] = []string{parsed.Scheme}
	}
	basePath := parsed.Path
	if basePath == "" {
		basePath = "/"
	}
	doc["basePath"] = basePath
}
